### ISSUE TITLE
Web scraped data pretraining 

### ISSUE THREAD

**Issue by edmondja** [dhansmair/flamingo-mini#1]
As discussed here https://github.com/lucidrains/flamingo-pytorch/issues/4#issuecomment-1242723715, pretraining on CLIP can be problematic.
Can you suggest another parameter than openai/clip-vit-base-patch32 for the vision encoder, something more task agnostic ?
I am struggling with XRay images.

**Comment by dhansmair** [comment]
Hi @edmondja, 
the `FlamingoModel` class is actually independent of the vision encoder. The vision encoder is part of `FlamingoProcessor` which uses the `clip_model_type` parameter to instantiate it. For the flamingo model, only the `dim_visual` parameter is relevant. For example, the clip-vit-base produces visual features of the shape (50 x 768) and the flamingo model uses that as input.
If you want to use a task agnostic vision encoder, you could e.g. inherit from FlamingoProcessor and replace the vision encoder with your own.

Does that help?

**Comment by edmondja** [comment]
Yes my question was more about where to find the accepted parameters list and maybe if you had any suggestion. Sorry if my question was not clear enough

**Comment by dhansmair** [comment]
I'm not aware of vision encoders trained for specific types of images. The pretrained models you can use without modification are hosted on https://huggingface.co/openai. They also have ResNet versions (https://github.com/openai/CLIP/blob/main/model-card.md#model-versions) which are not on huggingface and can't be used out of the box.

**Comment by edmondja** [comment]
Ah ok thanks !
