### ISSUE TITLE
Bugs of evaluation / caption generation

### ISSUE THREAD

**Issue by evelinehong** [dhansmair/flamingo-mini#13]
1. self.visuals -> self.encode_resample_visuals
2. media_locations shape not consistent with attention_masks, causing an error at 
`sim = sim.masked_fill(~text_to_media_mask, -torch.finfo(sim.dtype).max)`
`The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 2`

**Comment by dhansmair** [comment]
Hi @evelinehong, could you provide a code snippet to reproduce the error?
Usually one would pass pixel_values to forward(). if you extract the visual features manually using encode_resample_visuals() , make sure the dimensions are correct, e.g. visual_features should have shape (b N T q d). Sometimes feature extraction messes up b (=batch size) and N (=number of images per sequence)

**Comment by evelinehong** [comment]
Oh nvm. I cloned the repository yesterday morning and there was an object dict error about the "past_key_values". I manually fixed the bug, which led to the "media_locations" bug (I think). I use the newest version and everything is fine now.

**Comment by dhansmair** [comment]
I'm glad to hear that. Ah yes, this past_key_values error was troubling other people as well with transformers > 4.25.1, it should be fixed now.
