### ISSUE TITLE
About the training script

### ISSUE THREAD

**Issue by kenchan0226** [dhansmair/flamingo-mini#16]
Thanks for this excellent work. 
In the README, you mentioned that the training script is available at https://github.com/dhansmair/flamingo-mini/tree/hf_trainer. However, this url returns page not found. Could you please let me know the correct url to the training script?

**Comment by dhansmair** [comment]
Hi, you are right, I forgot to update that part of the README. I moved the script to the main branch, its https://github.com/dhansmair/flamingo-mini/blob/main/training/train.py .
But it's really just a basic one, you'll need to adapt it to your needs.
