### ISSUE TITLE
Error on image_captioning.ipynb

### ISSUE THREAD

**Issue by tomasmadeira** [dhansmair/flamingo-mini#9]
![Screenshot 2023-01-23 103244](https://user-images.githubusercontent.com/71838048/214006784-e45387b2-4538-4c14-b980-f3796539cd26.png)

Error when running `caption = model.generate_captions(processor, images=[image])` in image_captioning.ipynb

What is the best way to generate inference from code?

Also tried pipeline, but am missing `use_auth_token`.
pipe = pipeline(task='image-to-text', model='dhansmair/flamingo')

Thanks in advance! Great work

**Comment by dhansmair** [comment]
Hi @tomasmadeira, thank you for reporting this problem!
The example provided in image_captioning.ipynb works for me. Did you modify the code? If so, could you provide it so I can reproduce the problem? Maybe the code also breaks with a different transformers version, mine is 4.25.1 at the moment.

As to pipeline, I haven't used it yet so I don't know if my implementation integrates with it. But the model string should be 'dhansmair/flaming-tiny' or 'dhansmair/flamingo-mini', and you shouldn't require a token to access it

**Comment by tomasmadeira** [comment]
Hi @dhansmair, thanks for the quick reply! It was a problem with the package versioning and kernels. Works now :)
